#!/bin/bash
#
# list.sh 
# This script generates a table of data set information from the output of dials.
#
# The original script was generated by Dr. Takanori Nakane, and modified 
# to fit the MicroED operation in Tsukuba University.
## The original version is distribure in https://github.com/GKLabIPR/MicroED/

SUFFIX=$1

HEADER="|        Data set        | Dmin  | Laue group | Cmplt | WilsonB |               P1 cell parameter                 |"
echo "${HEADER}"
for f in */dials.scale${SUFFIX}.log; do
    DIR=`dirname $f | cut -d/ -f1,2`
    RESO=$(awk '/cc_ano/ {f=1; b=999; next}
         f==1 && $13 > 0.3 {b = $2;}
         f==1 && $13 <= 0.3 {printf b; exit}' $f)
    LAUE=$(grep "Best sol" $DIR/dials.symmetry${SUFFIX}.log| tr -d '\n' | sed 's/Best solution: //g')
    CELL=$(awk '/Unit cell/ {printf $3" "$4" "$5" "$6" "$7" "$8}' $DIR/dials.integrate.log)
    CMPLT=$(awk '/^Completeness/ {printf $2;}' $DIR/dials.merge${SUFFIX}.log)
    BISO=$(awk '/^Wilson B factor/ {printf $4;}' $DIR/dials.merge${SUFFIX}.log)
    printf "| %22s |" "$DIR"
    printf " %5s |" "$RESO"
    printf " %-10s |" "$LAUE"
    printf " %5s |" "$CMPLT"
    printf " %7s |" "$BISO"
    for j in $CELL;
    do
	    printf "%6s, " $(echo $j | awk '{printf substr($1,0,index($1,".")+1)}') 
    done
    printf " |\n"
done > TEST.TXT

sort -k 4  TEST.TXT

rm TEST.TXT
