#!/bin/bash
# 
# merge.sh
#
# This script pick up data sets from the list file generated by
# list.sh and merge them.
#

STATS_LIST=$1
TRESHOLD=$2
DMIN_SCALE=$3

if [ "${DMIN_SCALE}" != "" ]; then
	SCALE_PARAM="d_min=${DMIN_SCALE}"
else
	SCALE_PARAM=""
fi

DATASETS=$(cat ${STATS_LIST} | awk -v thresh=${TRESHOLD} '$4<thresh {printf("../%s/not_blank.expt ../%s/not_blank.refl ", $2, $2)}')
DATASETS=${DATASETS::-1}

echo ${DATASETS}

dials.cosym ${DATASETS}
dials.two_theta_refine output.cif=refined_cell.cif symmetrized.{expt,refl}
dials.scale refined_cell.expt symmetrized.refl ${SCALE_PARAM} \
	filtering.method=deltacchalf \
	output.unmerged_mtz=scaled.mtz \
	output.merged_mtz=merged.mtz
